/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_business_SubProcess */

#ifndef _Included_com_example_test_business_SubProcess
#define _Included_com_example_test_business_SubProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_business_SubProcess
 * Method:    getWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_business_SubProcess_getWord
  (JNIEnv *, jclass);

/*
 * Class:     com_example_test_business_SubProcess
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_business_SubProcess_getHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
